# Generated by Django 3.1.7 on 2022-01-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='stud_list',
        ),
        migrations.AlterField(
            model_name='user',
            name='college_name',
            field=models.CharField(blank=True, default='计算机学院', max_length=150, verbose_name='学院全称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='电子邮件'),
        ),
        migrations.AlterField(
            model_name='user',
            name='internal_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='学工号'),
        ),
    ]
