# Generated by Django 3.1.7 on 2021-04-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='join_status',
            field=models.IntegerField(choices=[(0, '名单之外'), (1, '未加入'), (2, '已加入'), (3, '管理员')], default=0, verbose_name='加入状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='priority',
            field=models.IntegerField(choices=[(0, '学生'), (1, '教师'), (2, '管理员')], default=0, verbose_name='权限等级'),
        ),
    ]
