# Generated by Django 3.1.7 on 2022-02-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录ID')),
                ('full_name', models.CharField(max_length=30, verbose_name='学生姓名')),
                ('internal_id', models.CharField(max_length=30, verbose_name='学号')),
                ('join_code', models.CharField(max_length=20, verbose_name='班级识别码')),
                ('join_status', models.BooleanField(default=False, verbose_name='加入状态')),
            ],
            options={
                'verbose_name': '学生清单',
                'verbose_name_plural': '学生清单',
            },
        ),
    ]
