# Generated by Django 3.1.7 on 2022-02-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_name',
            field=models.CharField(max_length=150, verbose_name='班级名称'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(default='西北工业大学', max_length=150, unique=True, verbose_name='学校全称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=150, primary_key=True, serialize=False, verbose_name='电子邮件'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
