# Generated by Django 3.1.7 on 2022-02-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='need_list',
            field=models.BooleanField(default=True, verbose_name='需要学生清单'),
        ),
    ]
