# Generated by Django 3.1.7 on 2022-02-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220206_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='join_code',
            field=models.CharField(default=123, max_length=20, verbose_name='班级识别码'),
            preserve_default=False,
        ),
    ]
