# Generated by Django 3.1.7 on 2022-02-27 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_studentlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlist',
            name='join_code',
        ),
        migrations.AddField(
            model_name='studentlist',
            name='classroom',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.classroom', verbose_name='班级'),
        ),
    ]
