# Generated by Django 3.1.7 on 2022-02-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220227_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlist',
            name='classroom',
        ),
        migrations.AddField(
            model_name='studentlist',
            name='join_code',
            field=models.CharField(default=123, max_length=20, verbose_name='班级识别码'),
            preserve_default=False,
        ),
    ]
