# Generated by Django 3.1.7 on 2021-04-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210407_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_id', models.CharField(max_length=150, verbose_name='学校ID')),
                ('class_name', models.CharField(max_length=150, verbose_name='班级名称')),
                ('teacher_name', models.CharField(max_length=150, verbose_name='教师姓名')),
                ('class_desc', models.CharField(max_length=200, verbose_name='班级描述')),
                ('stud_list', models.CharField(max_length=2000, verbose_name='学生列表')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False, verbose_name='学校ID')),
                ('school_name', models.CharField(default='西北工业大学', max_length=150, verbose_name='学校全称')),
                ('school_name_en', models.CharField(default='Northwestern Polytechnical University', max_length=150, verbose_name='学校英文全称')),
                ('school_abbr', models.CharField(default='NPU', max_length=50, verbose_name='学校英文缩写')),
            ],
        ),
    ]
