# Generated by Django 3.1.7 on 2021-04-23 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_classroom_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
            ],
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': '班级', 'verbose_name_plural': '班级'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '学校', 'verbose_name_plural': '学校'},
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='school_id',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.school', to_field='school_name', verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='class_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='班级ID'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_abbr',
            field=models.CharField(default='NPU', max_length=50, unique=True, verbose_name='学校英文缩写'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(default='西北工业大学', max_length=150, unique=True, verbose_name='学校全称'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name_en',
            field=models.CharField(default='Northwestern Polytechnical University', max_length=150, unique=True, verbose_name='学校英文全称'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.teacher', verbose_name='教师姓名'),
        ),
    ]
