# Generated by Django 3.1.7 on 2022-02-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220227_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlist',
            name='join_code',
        ),
    ]
