# Generated by Django 3.1.7 on 2022-02-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_studentlist_join_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentList',
        ),
    ]
