# Generated by Django 3.1.7 on 2022-02-27 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_studentlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录ID')),
                ('full_name', models.CharField(max_length=30, verbose_name='学生姓名')),
                ('internal_id', models.CharField(max_length=30, verbose_name='学号')),
                ('join_status', models.BooleanField(default=False, verbose_name='加入状态')),
                ('classroom', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.classroom', verbose_name='班级')),
            ],
            options={
                'verbose_name': '学生清单',
                'verbose_name_plural': '学生清单',
            },
        ),
    ]
