# Generated by Django 3.1.7 on 2021-04-23 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210423_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='class_id',
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.classroom', verbose_name='班级'),
        ),
    ]
