# Generated by Django 3.1.7 on 2022-02-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_studentlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='internal_id',
            field=models.CharField(max_length=31, verbose_name='学号'),
        ),
    ]
