# Generated by Django 3.1.7 on 2021-04-23 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210423_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='班级描述'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.school', verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='stud_list',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='学生列表'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.teacher', verbose_name='教师'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.classroom', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.school', verbose_name='学校'),
        ),
    ]
