# Generated by Django 3.1.7 on 2021-04-23 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210423_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_desc',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='班级描述'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.teacher', verbose_name='负责教师'),
        ),
    ]
