# Generated by Django 3.1.7 on 2021-04-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210423_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='班级描述'),
        ),
    ]
