# Generated by Django 3.1.7 on 2021-04-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210424_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='join_status',
            field=models.BooleanField(default=False, verbose_name='加入状态'),
        ),
    ]
