# Generated by Django 3.1.7 on 2022-02-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20220227_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='join_status',
        ),
    ]
