# Generated by Django 3.1.7 on 2021-05-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_student_join_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='active',
            field=models.BooleanField(default=True, verbose_name='有效状态'),
        ),
    ]
