# Generated by Django 3.1.7 on 2021-04-24 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0010_auto_20210424_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paper_id', models.AutoField(primary_key=True, serialize=False, verbose_name='试卷ID')),
                ('paper_name', models.CharField(max_length=100, verbose_name='试卷名称')),
                ('paper_type', models.IntegerField(choices=[(0, '练习'), (1, '考试')], verbose_name='试卷类型')),
                ('publish_time', models.DateTimeField(verbose_name='发布时间')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('paper_active', models.BooleanField(default=False, verbose_name='发布状态')),
                ('paper_desc', models.TextField(null=True, verbose_name='试卷描述')),
                ('classroom', models.ManyToManyField(to='user.Classroom', verbose_name='分配班级')),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.teacher', verbose_name='发起人')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('ques_set_id', models.AutoField(primary_key=True, serialize=False, verbose_name='题库ID')),
                ('ques_set_name', models.CharField(max_length=100, verbose_name='题库名称')),
                ('ques_set_desc', models.TextField(verbose_name='题库描述')),
                ('create_sql', models.TextField(verbose_name='创建SQL')),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.teacher', verbose_name='发起人')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('ques_id', models.AutoField(primary_key=True, serialize=False, verbose_name='题目ID')),
                ('ques_name', models.CharField(default='未命名题目', max_length=100, null=True, verbose_name='题目名称')),
                ('ques_difficulty', models.IntegerField(choices=[(-1, '位置'), (0, '简单'), (1, '中等'), (2, '困难')], default=-1, verbose_name='题目难度')),
                ('ques_desc', models.TextField(verbose_name='题目描述')),
                ('ques_ans', models.TextField(verbose_name='标准答案')),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.teacher', verbose_name='发起人')),
                ('ques_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.questionset', verbose_name='所属题库')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
            },
        ),
        migrations.CreateModel(
            name='QuesAnswerRec',
            fields=[
                ('rec_id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录ID')),
                ('ans_status', models.BooleanField(default=False, verbose_name='答案正确性')),
                ('submit_cnt', models.IntegerField(default=0, verbose_name='提交次数')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coding.question', verbose_name='题目')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '题目作答记录',
                'verbose_name_plural': '题目作答记录',
            },
        ),
        migrations.CreateModel(
            name='PaperAnswerRec',
            fields=[
                ('rec_id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='交卷时间')),
                ('score', models.IntegerField(default=0, verbose_name='总成绩')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coding.paper', verbose_name='题目')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '试卷作答记录',
                'verbose_name_plural': '试卷作答记录',
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='question',
            field=models.ManyToManyField(to='coding.Question', verbose_name='题目列表'),
        ),
    ]
