# Generated by Django 3.1.7 on 2022-09-23 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanswerrec',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.exam', verbose_name='考试'),
        ),
        migrations.AlterField(
            model_name='exeranswerrec',
            name='exer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.exercise', verbose_name='练习'),
        ),
    ]
