# Generated by Django 3.1.7 on 2022-02-23 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='exam',
        #     name='show_answer',
        # ),
    ]
