# Generated by Django 3.1.7 on 2021-04-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_desc',
            field=models.TextField(blank=True, null=True, verbose_name='试卷描述'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques_difficulty',
            field=models.IntegerField(choices=[(-1, '未知'), (0, '简单'), (1, '中等'), (2, '困难')], default=-1, verbose_name='题目难度'),
        ),
    ]
