# Generated by Django 3.1.7 on 2022-10-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_auto_20220923_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquesanswerrec',
            name='error_info',
            field=models.TextField(blank=True, null=True, verbose_name='作答错误信息(仅错误时有)'),
        ),
        migrations.AddField(
            model_name='exerquesanswerrec',
            name='error_info',
            field=models.TextField(blank=True, null=True, verbose_name='作答错误信息(仅错误时有)'),
        ),
    ]
