# Generated by Django 3.1.7 on 2021-05-16 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_student_join_status'),
        ('coding', '0002_auto_20210424_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='paper_active',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='paper_type',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='paperanswerrec',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coding.paper', verbose_name='试卷'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques_name',
            field=models.CharField(default='未命名', max_length=100, null=True, verbose_name='题目名称'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='ques_set_desc',
            field=models.TextField(blank=True, null=True, verbose_name='题库描述'),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='练习ID')),
                ('exer_name', models.CharField(default='未命名', max_length=100, verbose_name='练习名称')),
                ('publish_time', models.DateTimeField(default=None, verbose_name='发布时间')),
                ('active', models.BooleanField(default=False, verbose_name='发布状态')),
                ('classroom', models.ManyToManyField(to='user.Classroom', verbose_name='分配班级')),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coding.paper', verbose_name='试卷')),
            ],
            options={
                'verbose_name': '练习',
                'verbose_name_plural': '练习',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False, verbose_name='考试ID')),
                ('exam_name', models.CharField(default='未命名', max_length=100, verbose_name='考试名称')),
                ('start_time', models.DateTimeField(default=None, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default=None, verbose_name='结束时间')),
                ('publish_time', models.DateTimeField(default=None, verbose_name='发布时间')),
                ('active', models.BooleanField(default=False, verbose_name='发布状态')),
                ('classroom', models.ManyToManyField(to='user.Classroom', verbose_name='分配班级')),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coding.paper', verbose_name='试卷')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
            },
        ),
    ]
