# Generated by Django 3.1.7 on 2022-02-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_remove_exam_show_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='show_answer',
            field=models.BooleanField(default=False, verbose_name='在解析中公布答案'),
        ),
    ]
