# Generated by Django 3.1.7 on 2022-01-07 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_questionset_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionset',
            name='share',
        ),
    ]
