# Generated by Django 3.1.7 on 2022-01-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0003_remove_questionset_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='share',
            field=models.BooleanField(default=False, verbose_name='其他老师可查看'),
        ),
    ]
