# Generated by Django 3.1.7 on 2022-10-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0003_auto_20221007_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquesanswerrec',
            name='error_info',
            field=models.TextField(blank=True, null=True, verbose_name='作答异常信息(仅异常时有)'),
        ),
        migrations.AlterField(
            model_name='exerquesanswerrec',
            name='error_info',
            field=models.TextField(blank=True, null=True, verbose_name='作答异常信息(仅异常时有)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques_desc',
            field=models.TextField(verbose_name='题目要求'),
        ),
    ]
