# Generated by Django 3.1.7 on 2022-02-03 08:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0003_auto_20220203_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.paper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.question')),
            ],
            options={
                'db_table': 'Paper_Question_relationship',
            },
        ),
        migrations.DeleteModel(
            name='Questionswithscore',
        ),
    ]
