# Generated by Django 3.1.7 on 2022-02-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0004_auto_20220203_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='question',
        ),
        migrations.AddField(
            model_name='paper',
            name='question',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
