# Generated by Django 3.1.7 on 2021-05-18 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0004_auto_20210518_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.paper', verbose_name='试卷'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.paper', verbose_name='试卷'),
        ),
    ]
