# Generated by Django 3.1.7 on 2022-02-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0005_auto_20220203_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='question',
        ),
        migrations.AddField(
            model_name='paper',
            name='question',
            field=models.ManyToManyField(through='coding.PaperQuestion', to='coding.Question', verbose_name='题目列表'),
        ),
    ]
