# Generated by Django 3.1.7 on 2021-05-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0005_auto_20210518_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='db_name',
            field=models.CharField(default='null', editable=False, max_length=100, verbose_name='数据库名称'),
        ),
    ]
