# Generated by Django 3.1.7 on 2022-01-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0006_paper_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperanswerrec',
            name='paper_class',
            field=models.IntegerField(choices=[(-1, '未知'), (0, '考试'), (1, '练习')], default=-1, verbose_name='试卷类型'),
        ),
    ]
