# Generated by Django 3.1.7 on 2022-02-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0006_auto_20220203_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperquestion',
            name='publish_at',
        ),
        migrations.AddField(
            model_name='paperquestion',
            name='score',
            field=models.IntegerField(default=10),
        ),
    ]
