# Generated by Django 3.1.7 on 2021-05-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0006_questionset_db_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='db_name',
            field=models.CharField(default='null', max_length=100, verbose_name='数据库名称'),
        ),
    ]
