# Generated by Django 3.1.7 on 2022-01-18 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('coding', '0007_paperanswerrec_paper_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paperanswerrec',
            options={'verbose_name': '试卷作答记录(*)', 'verbose_name_plural': '试卷作答记录(*)'},
        ),
        migrations.AlterModelOptions(
            name='quesanswerrec',
            options={'verbose_name': '题目作答记录(*)', 'verbose_name_plural': '题目作答记录(*)'},
        ),
        migrations.CreateModel(
            name='ExerAnswerRec',
            fields=[
                ('rec_id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='交卷时间')),
                ('score', models.IntegerField(default=0, verbose_name='总成绩')),
                ('exer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coding.exercise', verbose_name='练习')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '考试作答记录(**)',
                'verbose_name_plural': '考试作答记录(**)',
            },
        ),
        migrations.CreateModel(
            name='ExamAnswerRec',
            fields=[
                ('rec_id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='交卷时间')),
                ('score', models.IntegerField(default=0, verbose_name='总成绩')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coding.exam', verbose_name='考试')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '考试作答记录(**)',
                'verbose_name_plural': '考试作答记录(**)',
            },
        ),
    ]
