# Generated by Django 3.1.7 on 2022-02-03 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0008_auto_20220118_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exeranswerrec',
            options={'verbose_name': '练习作答记录(**)', 'verbose_name_plural': '练习作答记录(**)'},
        ),
        migrations.CreateModel(
            name='PaperQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=10)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.paper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.question')),
            ],
            options={
                'db_table': 'Paper_Question_relationship',
            },
        ),
    ]
