# Generated by Django 3.1.7 on 2021-05-25 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0011_auto_20210521_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesanswerrec',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coding.question', verbose_name='题目'),
        ),
    ]
