# Generated by Django 3.1.7 on 2022-02-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0012_auto_20220203_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paperquestion',
            options={'verbose_name': '试卷', 'verbose_name_plural': '试卷'},
        ),
    ]
