# Generated by Django 3.1.7 on 2021-05-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0012_auto_20210525_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesanswerrec',
            name='ans',
            field=models.TextField(blank=True, null=True, verbose_name='上次答案'),
        ),
    ]
