# Generated by Django 3.1.7 on 2021-05-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0013_quesanswerrec_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesanswerrec',
            name='ans',
            field=models.TextField(blank=True, null=True, verbose_name='最新答案'),
        ),
    ]
