# Generated by Django 3.1.7 on 2022-02-03 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0013_auto_20220203_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paperquestion',
            options={'verbose_name': '题目和分值', 'verbose_name_plural': '题目和分值'},
        ),
    ]
