# Generated by Django 3.1.7 on 2021-05-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0014_auto_20210525_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesanswerrec',
            name='submit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后提交时间'),
        ),
    ]
