# Generated by Django 3.1.7 on 2022-02-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0015_auto_20220203_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanswerrec',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='交卷时间'),
        ),
        migrations.AlterField(
            model_name='examanswerrec',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='总成绩'),
        ),
    ]
