# Generated by Django 3.1.7 on 2022-02-06 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coding', '0017_auto_20220206_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerQuesAnswerRec',
            fields=[
                ('rec_id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录ID')),
                ('ans', models.TextField(blank=True, null=True, verbose_name='最新答案')),
                ('ans_status', models.IntegerField(choices=[(-1, '未知'), (0, '答案正确'), (1, '答案错误'), (2, '运行异常')], default=-1, verbose_name='答案正确性')),
                ('submit_time', models.DateTimeField(auto_now=True, verbose_name='最后提交时间')),
                ('submit_cnt', models.IntegerField(default=0, verbose_name='提交次数')),
                # ('exer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coding.exercise', verbose_name='对应练习')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coding.question', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '题目作答记录(考试**)',
                'verbose_name_plural': '题目作答记录(考试**)',
            },
        ),
        migrations.CreateModel(
            name='ExamQuesAnswerRec',
            fields=[
                ('rec_id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录ID')),
                ('ans', models.TextField(blank=True, null=True, verbose_name='最新答案')),
                ('ans_status', models.IntegerField(choices=[(-1, '未知'), (0, '答案正确'), (1, '答案错误'), (2, '运行异常')], default=-1, verbose_name='答案正确性')),
                ('submit_time', models.DateTimeField(auto_now=True, verbose_name='最后提交时间')),
                ('submit_cnt', models.IntegerField(default=0, verbose_name='提交次数')),
                # ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coding.exam', verbose_name='对应考试')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coding.question', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '题目作答记录(考试**)',
                'verbose_name_plural': '题目作答记录(考试**)',
            },
        ),
    ]
