# Generated by Django 3.1.7 on 2022-02-06 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0018_examquesanswerrec_exerquesanswerrec'),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name='exerquesanswerrec',
        #     options={'verbose_name': '题目作答记录(练习**)', 'verbose_name_plural': '题目作答记录(练习**)'},
        # ),
        # migrations.AddField(
        #     model_name='examquesanswerrec',
        #     name='exam',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coding.exam', verbose_name='对应考试ID'),
        # ),
        # migrations.AddField(
        #     model_name='exerquesanswerrec',
        #     name='exer',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coding.exercise', verbose_name='对应练习ID'),
        # ),
    ]
