# Generated by Django 3.1.7 on 2022-02-06 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0019_auto_20220206_1109'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='exerquesanswerrec',
        #     name='exer',
        # ),
        # migrations.RemoveField(
        #     model_name='exerquesanswerrec',
        #     name='question',
        # ),
        # migrations.RemoveField(
        #     model_name='exerquesanswerrec',
        #     name='user',
        # ),
        migrations.DeleteModel(
            name='ExamQuesAnswerRec',
        ),
        migrations.DeleteModel(
            name='ExerQuesAnswerRec',
        ),
    ]
