# Generated by Django 3.1.7 on 2022-02-06 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0021_examquesanswerrec'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamQuesAnswerRec',
        ),
    ]
