# Generated by Django 3.1.7 on 2022-02-06 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0023_quesanswerrec2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quesanswerrec2',
            name='ans',
        ),
        migrations.RemoveField(
            model_name='quesanswerrec2',
            name='ans_status',
        ),
        migrations.RemoveField(
            model_name='quesanswerrec2',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quesanswerrec2',
            name='submit_cnt',
        ),
        migrations.RemoveField(
            model_name='quesanswerrec2',
            name='submit_time',
        ),
        migrations.RemoveField(
            model_name='quesanswerrec2',
            name='user',
        ),
    ]
