# Generated by Django 3.1.7 on 2022-02-06 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coding', '0024_auto_20220206_1119'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='quesanswerrec2',
        #     name='user',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户'),
        #     preserve_default=False,
        # ),
    ]
