# Generated by Django 3.1.7 on 2022-02-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0025_quesanswerrec2_user'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='quesanswerrec2',
        #     name='user',
        # ),
    ]
