# Generated by Django 3.1.7 on 2022-02-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0028_quesanswerrec2'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesanswerrec2',
            name='submit_cnt',
            field=models.IntegerField(default=0, verbose_name='提交次数'),
        ),
    ]
