# Generated by Django 3.1.7 on 2022-02-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0030_quesanswerrec2_submit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesanswerrec2',
            name='ans_status',
            field=models.IntegerField(choices=[(-1, '未知'), (0, '答案正确'), (1, '答案错误'), (2, '运行异常')], default=-1, verbose_name='答案正确性'),
        ),
    ]
