# Generated by Django 3.1.7 on 2022-02-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0031_quesanswerrec2_ans_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesanswerrec2',
            name='ans',
            field=models.TextField(blank=True, null=True, verbose_name='最新答案'),
        ),
    ]
