# Generated by Django 3.1.7 on 2022-02-06 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0032_quesanswerrec2_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesanswerrec2',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coding.question', verbose_name='题目'),
        ),
    ]
