# Generated by Django 3.1.7 on 2022-02-06 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0039_auto_20220206_1618'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='examquesanswerrec',
        #     name='exam',
        # ),
        # migrations.RemoveField(
        #     model_name='exerquesanswerrec',
        #     name='exer',
        # ),
    ]
