# Generated by Django 3.1.7 on 2022-02-06 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0040_auto_20220206_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquesanswerrec',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coding.examanswerrec', verbose_name='对应考试'),
        ),
        migrations.AlterField(
            model_name='exerquesanswerrec',
            name='exer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coding.exeranswerrec', verbose_name='对应练习'),
        ),
    ]
