# Generated by Django 3.1.7 on 2022-02-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0041_auto_20220206_2114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamQuesAnswerRec',
        ),
        migrations.DeleteModel(
            name='ExerQuesAnswerRec',
        ),
    ]
