# Generated by Django 3.1.7 on 2022-02-06 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0043_examquesanswerrec_exerquesanswerrec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquesanswerrec',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coding.examanswerrec', verbose_name='对应考试记录'),
        ),
        migrations.AlterField(
            model_name='exerquesanswerrec',
            name='exer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coding.exeranswerrec', verbose_name='对应练习记录'),
        ),
    ]
