# Generated by Django 3.1.7 on 2022-02-10 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220206_1124'),
        ('coding', '0044_auto_20220206_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswerrec',
            name='classroom',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.classroom', verbose_name='班级'),
        ),
    ]
