# Generated by Django 3.1.7 on 2022-02-10 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0045_examanswerrec_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examanswerrec',
            name='classroom',
        ),
    ]
