# Generated by Django 3.1.7 on 2022-02-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0046_remove_examanswerrec_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='end_time',
            field=models.DateTimeField(default=None, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='start_time',
            field=models.DateTimeField(default=None, verbose_name='开始时间'),
        ),
    ]
