# Generated by Django 3.1.7 on 2022-02-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0047_auto_20220210_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswerrec',
            name='mark_status',
            field=models.BooleanField(default=False, verbose_name='阅卷状态'),
        ),
        migrations.AddField(
            model_name='exeranswerrec',
            name='mark_status',
            field=models.BooleanField(default=False, verbose_name='阅卷状态'),
        ),
        migrations.AlterField(
            model_name='quesanswerrec',
            name='ans_status',
            field=models.IntegerField(choices=[(-1, '未知'), (0, '答案正确'), (1, '答案错误'), (2, '运行异常'), (3, '正在运行')], default=-1, verbose_name='答案正确性'),
        ),
    ]
