# Generated by Django 3.1.7 on 2022-02-13 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0049_auto_20220212_1020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaperAnswerRec',
        ),
    ]
