# Generated by Django 3.1.7 on 2022-02-13 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0051_delete_quesanswerrec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examanswerrec',
            options={'verbose_name': '考试作答记录', 'verbose_name_plural': '考试作答记录'},
        ),
        migrations.AlterModelOptions(
            name='examquesanswerrec',
            options={'verbose_name': '题目作答记录(考试)', 'verbose_name_plural': '题目作答记录(考试)'},
        ),
        migrations.AlterModelOptions(
            name='exeranswerrec',
            options={'verbose_name': '练习作答记录', 'verbose_name_plural': '练习作答记录'},
        ),
        migrations.AlterModelOptions(
            name='exerquesanswerrec',
            options={'verbose_name': '题目作答记录(练习)', 'verbose_name_plural': '题目作答记录(练习)'},
        ),
    ]
